apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "tester.fullname" . }}-config
  labels:
    {{- include "tester.labels" . | nindent 4 }}
data:
  BASE_URL: {{ .Values.env.BASE_URL | quote }}
  CRON_SCHEDULE: {{ .Values.env.CRON_SCHEDULE | quote }}
  K6_PROM_URL: {{ .Values.env.K6_PROM_URL | quote }}
  DEVICE_SECRET: {{ .Values.env.DEVICE_SECRET | quote }}
