apiVersion: v1
kind: Service
metadata:
  name: {{ include "tester.fullname" . }}
  labels:
    {{- include "tester.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 3000
      protocol: TCP
      name: http
  selector:
    {{- include "tester.selectorLabels" . | nindent 4 }}
