apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: testere-ingress
  namespace: testere
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
spec:
  ingressClassName: nginx
  rules:
  - host: testere.apps.getapp.sh
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: testere-service
            port:
              number: 80
  tls:
    - hosts:
        - testere.apps.getapp.sh
      secretName: testere
