apiVersion: v1
kind: Service
metadata:
  name: tester-service
  namespace: tester
spec:
  selector:
    app: tester
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000
  type: ClusterIP
